# 项目全局配置文件
# 用户只需修改本文件即可适配不同任务

# 数据相关
# 原始数据文件路径（相对路径）
data_path: "data/16_ML.csv"
# 主要暴露变量名
exposure: "DII_food"
# 结局变量名
outcome: "Epilepsy"
# 协变量列表
covariates: ["Gender", "Age", "BMI", "Education", "Marriage", "Smoke", "Alcohol", "Employment", "ActivityLevel"]

# 模型训练次数
n_trials: 10

# 目标函数权重
objective_weights:
  AUC: 0.25
  ECE: -0.2
  F1: 0.2
  Precision: 0.3
  Sensitivity: 0.25
  Specificity: 0.2

# 目标函数硬约束 - 分为交叉验证和测试集两套约束
# 交叉验证约束（较宽松）
cv_constraints:
  AUC_min: 0.6
  AUC_max: 0.99  # 提高AUC上限，允许更好的模型通过
  Sensitivity_min: 0.4
  Specificity_min: 0.4  # 提高特异度最低要求，改善精确度

# 测试集约束（较严格）
test_constraints:
  AUC_min: 0.65
  AUC_max: 0.9
  Sensitivity_min: 0.5
  Specificity_min: 0.5

# 兼容原有配置
objective_constraints:
  AUC_min: 0.7
  AUC_max: 0.9
  Sensitivity_min: 0.5
  Specificity_min: 0.5

# CatBoost GPU
catboost_task_type: "GPU"

# 评估与绘图设置
eval_settings:
  calc_metrics: 1      # 是否计算评估指标(1:是, 0:否)
  draw_roc: 1          # 是否绘制ROC曲线(1:是, 0:否)
  draw_pr: 1           # 是否绘制PR曲线(1:是, 0:否)
  draw_calibration: 1  # 是否绘制校准曲线(1:是, 0:否)
  draw_confusion: 1    # 是否绘制混淆矩阵(1:是, 0:否)
  draw_learning: 0     # 是否绘制学习曲线(1:是, 0:否)
  draw_threshold: 1    # 是否绘制阈值曲线(1:是, 0:否)
  draw_dca: 1          # 是否绘制决策曲线分析(DCA)(1:是, 0:否)

# 输出相关
output_dir: "result/"
plot_dir: "plot/"
model_dir: "model/"
random_seed: 42

# 模型配置
models:
  # 模型显示顺序
  order:
    - "Logistic"
    - "CatBoost"
    - "FNN"
    - "LightGBM"
    - "GNB"
    - "RF"
    - "XGBoost"
    - "Ensemble_Voting"
  
  # 模型显示名称
  display_names:
    XGBoost: "XGBoost"
    LightGBM: "LightGBM"
    CatBoost: "CatBoost"
    RF: "RF"
    FNN: "FNN"
    GNB: "GNB"
    Logistic: "Logistic"
    Ensemble_Voting: "Voting"
  
  # 模型颜色
  colors:
    XGBoost: "#1f77b4"      # 蓝色
    LightGBM: "#ff7f0e"     # 橙色
    CatBoost: "#2ca02c"     # 绿色
    RF: "#d62728"           # 红色
    FNN: "#9467bd"          # 紫色
    GNB: "#8c564b"         # 棕色
    Logistic: "#e377c2"     # 粉色
    Ensemble_Voting: "#17becf" # 青色
    Random: "gray"          # 随机分类器参考线
    Treat_All: "green"      # Treat All参考线
    Treat_None: "red"       # Treat None参考线
