# 项目全局配置文件
# 用户只需修改本文件即可适配不同任务

# 数据相关
# 原始数据文件路径（相对路径）
data_path: "data/16_ML.csv"
# 主要暴露变量名
exposure: "DII_food"
# 结局变量名
outcome: "Epilepsy"
# 协变量列表
covariates: ["Gender", "Age", "BMI", "Education", "Marriage", "Smoke", "Alcohol", "Employment", "ActivityLevel"]

# 模型训练次数
# 为了测试设置很小的值
n_trials: 2

# 目标函数权重
objective_weights:
  AUC: 0.3
  ECE: -0.1
  F1: 0.2
  Precision: 0.2
  Sensitivity: 0.2
  Specificity: 0.2

# 目标函数硬约束 - 分为交叉验证和测试集两套约束
# 交叉验证约束（较宽松）
cv_constraints:
  AUC_min: 0.6
  AUC_max: 0.95
  Sensitivity_min: 0.4
  Specificity_min: 0.4

# 测试集约束（较严格）
test_constraints:
  AUC_min: 0.7
  AUC_max: 0.9
  Sensitivity_min: 0.5
  Specificity_min: 0.5

# 兼容原有配置
objective_constraints:
  AUC_min: 0.7
  AUC_max: 0.9
  Sensitivity_min: 0.5
  Specificity_min: 0.5

# CatBoost GPU
catboost_task_type: "GPU"

# 输出相关
output_dir: "result/"
plot_dir: "plot/"
model_dir: "model/"
random_seed: 42
