# 项目全局配置文件
# 用户只需修改本文件即可适配不同任务

# 数据相关
# 原始数据文件路径（相对路径）
data_path: "data/16_ML.csv"
# 主要暴露变量名
exposure: "DII_food"
# 结局变量名
outcome: "Epilepsy"
# 协变量列表
covariates: ["Gender", "Age", "BMI", "Education", "Marriage", "Smoke", "Alcohol", "Employment", "ActivityLevel"]

# 模型训练次数
n_trials: 50

# 目标函数权重
objective_weights:
  AUC: 0.3
  ECE: -0.2  # 增加校准的重要性
  F1: 0.2
  Precision: 0.3  # 增加精确度的重要性
  Sensitivity: 0.2  # 降低敏感度的权重
  Specificity: 0.2  # 增加特异度的重要性

# 目标函数硬约束 - 分为交叉验证和测试集两套约束
# 交叉验证约束（较宽松）
cv_constraints:
  AUC_min: 0.6
  AUC_max: 0.99  # 提高AUC上限，允许更好的模型通过
  Sensitivity_min: 0.4
  Specificity_min: 0.6  # 提高特异度最低要求，改善精确度

# 测试集约束（较严格）
test_constraints:
  AUC_min: 0.7
  AUC_max: 0.9
  Sensitivity_min: 0.5
  Specificity_min: 0.5

# 兼容原有配置
objective_constraints:
  AUC_min: 0.7
  AUC_max: 0.9
  Sensitivity_min: 0.5
  Specificity_min: 0.5

# CatBoost GPU
catboost_task_type: "GPU"

# 评估与绘图设置
eval_settings:
  calc_metrics: 1      # 是否计算评估指标(1:是, 0:否)
  draw_roc: 1          # 是否绘制ROC曲线(1:是, 0:否)
  draw_pr: 1           # 是否绘制PR曲线(1:是, 0:否)
  draw_calibration: 1  # 是否绘制校准曲线(1:是, 0:否)
  draw_confusion: 1    # 是否绘制混淆矩阵(1:是, 0:否)
  draw_learning: 0     # 是否绘制学习曲线(1:是, 0:否)
  draw_threshold: 1    # 是否绘制阈值曲线(1:是, 0:否)
  draw_dca: 1          # 是否绘制决策曲线分析(DCA)(1:是, 0:否)

# 输出相关
output_dir: "result/"
plot_dir: "plot/"
model_dir: "model/"
random_seed: 42
